services:
  guhemama.http_precondition.default_expression_language:
    class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

  guhemama.http_precondition.precondition_listener:
    class: Guhemama\HttpPreconditionBundle\EventListener\Request\PreconditionListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller_arguments }